### ISSUE TITLE
Module not showing

### ISSUE THREAD

**Issue by dameunaventon** [bitpay/prestashop-plugin#28]
Hi

Installed the bitpay v1.5 plugin on Prestashop 1.6.0.11

It's proprely installed but it doesn't show in the module list. I've tried to refresh and to empty the cache but nothing seems to work. The module just doesn't appear. 

Did anybody else experienced the same issue?

Thank

**Comment by philosodad** [comment]
The BitPay module is actually very easy to miss. It does not show up under payments, and the logo for the prestashop plugin is extremely fuzzy. One thing that can cause this is if the permissions for the BitPay plugin are not correct: that is, if the www-data user (or whichever user the rest of prestashop is owned by) doesn't own the bitpay files, they will not show up.

**Comment by dameunaventon** [comment]
Thank you, what is the fix?

**Comment by philosodad** [comment]
first check the permissions on the bitpay files. If they are different than the permissions of other files in the same folder, make them the same. This usually requires ssh or sftp access to the server. Also, make sure that you really can't see the module, as I said, it's actually fairly easy to miss.

How are you accessing your server to install the module?

**Comment by dameunaventon** [comment]
Sorry to ask this question, but how do you change the permissions on the bitpay files? Directly from the module files? If yes which one?

Thank you

**Comment by philosodad** [comment]
Straight from which prestashop panel? In order to install bitpay, you have to copy the bitpay files to your server, then install the bitpay module in your modules panel. What steps are you taking to install BitPay?

**Comment by dameunaventon** [comment]
well i thought that it was enough to upload it straight from my computer to the Prestashop admin panel. So should i upload it to my ftp and try to install it?

**Comment by alphaonex86** [comment]
dameunaventon: yes, maybe upload from ftp will fix. Sound like miss configured server. You sys admin  can fix it.

**Comment by philosodad** [comment]
Absolutely, the best thing to do is to use an ftp client to upload the plugin to your prestashop installation.

**Comment by ionux** [comment]
This issue should be fixed with the latest re-packaging of the plugin.  Please download the latest release and install.  The problem was how GitHub creates the zip file when you click the default Download button for this repository.

**Comment by dameunaventon** [comment]
Thank for your help. But i re installed the module, it still doesn't appear. Is there a workaround?

**Comment by dameunaventon** [comment]
@ionux Can you please help us find a workaround? I have tried to install the module a couple of times using the latest version but it's still not appearing. 

Also i have tried to upload the module directly to /public_html/themes/mytheme/modules but it doesn' t work either

Please let me know

Thank you

**Comment by brohemath** [comment]
I have tried everything, Using Presta's front end it says "module has been sucessfully downloaded"
but cannot find it in payment section, or any other section for that matter.
I uploaded the zip file directly to the presta module folder, unzipped it, but left the zipped file there, still not showing up in Presta's module selection, I selected ALL modules just to go through them and it is not there. I tried deleting the zipped file inside module directory still not showing up.
Is this a problem with Prestas front end or is it the zip file itself?

**Comment by ionux** [comment]
Are you using the zip file from the Releases page or the one you get from the main repository page when you click the "Download Zip" button?  You should be using the package from the Releases page here:https://github.com/bitpay/prestashop-plugin/releases/tag/v1.5.0

**Comment by brohemath** [comment]
ionux, I think that was it, it was the wrong file, luckily for me I had already installed bitpay on another site that shared a server so I was able to locate the bitpay module folder on that install and copy it into the other directory and then it showed up in Presta's front end.

**Comment by ionux** [comment]
Excellent!  Glad I could help.  @dameunaventon does that solve the problem for you, too?

**Comment by brohemath** [comment]
yes thank you, the file that did not work was named pretashop-plugin-master while the one I took from another installation was named; bitpay-prestashop-plugin-v1.5.0-27-g0e9d25d.zip.
I must say this is one of the easiest bitcoin modules I have ever had to install on Presta, it required no coding or all the usual methods you run across for many github bitcoin module installations, very happy I found this one.

**Comment by markshuai** [comment]
alphaonex86 i need someone to do sys admin service. for me,  can you email me at Markjstafford@gmail.com
